CREATE TABLE GEN_SEARCH_PARAMS 
(
  VIEW_NAME VARCHAR2(100) NOT NULL 
, MVIEW_NAME VARCHAR2(100) NOT NULL 
, COLUMN_NAME VARCHAR2(100) NOT NULL 
, COLUMN_DISPLAY_NAME VARCHAR2(200) NOT NULL 
, COLUMN_VISIBLE VARCHAR2(1) NOT NULL 
, COLUMN_FILTRABLE VARCHAR2(1) NOT NULL 
, COLUMN_OPERABLE VARCHAR2(1) NOT NULL 
, COLUMN_TYPE VARCHAR2(32) NOT NULL 
, COLUMN_FILTER_TYPE VARCHAR2(32) 
, CONSTRAINT GEN_SEARCH_P_PK PRIMARY KEY 
  (
    VIEW_NAME 
  , COLUMN_NAME 
  , MVIEW_NAME 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TABLE1_PK ON GEN_SEARCH_PARAMS (VIEW_NAME ASC, COLUMN_NAME ASC, MVIEW_NAME ASC) 
  )
  ENABLE 
);

COMMENT ON COLUMN GEN_SEARCH_PARAMS.VIEW_NAME IS 'Nombre de la vista';

COMMENT ON COLUMN GEN_SEARCH_PARAMS.MVIEW_NAME IS 'Nombre de la vista materializada';

COMMENT ON COLUMN GEN_SEARCH_PARAMS.COLUMN_NAME IS 'Nombre de la columna en las vistas';

COMMENT ON COLUMN GEN_SEARCH_PARAMS.COLUMN_DISPLAY_NAME IS 'Nombre de la columna en la aplicacion';

COMMENT ON COLUMN GEN_SEARCH_PARAMS.COLUMN_VISIBLE IS 'La columna se puede mostrar en la aplicacion';

COMMENT ON COLUMN GEN_SEARCH_PARAMS.COLUMN_FILTRABLE IS 'La columna se puede usar para filtrado';

COMMENT ON COLUMN GEN_SEARCH_PARAMS.COLUMN_OPERABLE IS 'La columna se puede usar para operaciones como el count';

COMMENT ON COLUMN GEN_SEARCH_PARAMS.COLUMN_TYPE IS 'Tipo de dato de la columna en la base';

COMMENT ON COLUMN GEN_SEARCH_PARAMS.COLUMN_FILTER_TYPE IS 'Que tipo de objeto es a la hora de usarse para filtrado en la app';
